{% set python_min = "3.12" %}
{% set version = "0.1.6" %}

package:
  name: kissbt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kissbt/kissbt-{{ version }}.tar.gz
  sha256: 24f3b6d8c50b6d8df31f341f2724418deb0decc756040e341987bb9b79df2801

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - kissbt
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/FinBlobs/kissbt
  license: Apache-2.0
  license_file: LICENSE
  summary: "The keep-it-simple backtesting framework for Python."

extra:
  recipe-maintainers:
    - adrianhasse
