{% set python_min = "3.10" %}
{% set version = "0.1.7" %}

package:
  name: kissbt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kissbt/kissbt-{{ version }}.tar.gz
  sha256: d8d0e3705f0a63b5a193846e7b57ff08989ab30477ca5bb89b1fc33fdaa082c7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - kissbt
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/FinBlobs/kissbt
  license: Apache-2.0
  license_file: LICENSE
  summary: "The keep-it-simple backtesting framework for Python."

extra:
  recipe-maintainers:
    - adrianhasse
